spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
  sql:
    init:
      mode: always
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    azure:
      passwordless-enabled: ${PASSWORDLESS_ENABLED:false}
      credential:
        managed-identity-enabled: ${MANAGED_IDENTITY_ENABLED:false}
proxy:
  enabled: false
forwarded-header:
  enabled: ${FORWARDED_HEADER_ENABLED:false}
server:
  forward-headers-strategy: ${FORWARDED_HEADERS_STRATEGY:native}
logging:
  level:
    org:
      springframework:
        security: DEBUG
